### ISSUE TITLE
[Suggestion] Add GitHub About for this repository

### ISSUE THREAD

**Issue by gomes042** [SergioRZMasson/BabylonReactNative-ReactNative0.65-Bugbash#10]
![image](https://user-images.githubusercontent.com/28831375/190255555-85429c56-cf5a-49b9-8ad3-02cbcea6a7f6.png)

Adding [description](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#description) field to [package.json](https://github.com/BabylonJS/BabylonReactNativeSample/blob/main/package.json) would also be interesting...

---------------------------------------------------------------------------

## Why? 
<img width="700px" src="https://user-images.githubusercontent.com/28831375/190255836-ba73e923-a00a-4862-9e46-7d1c371d6946.png"/>

https://reactnative.directory/

https://github.com/react-native-community/directory/pull/882

**Comment by runtothedoor** [comment]
@SergioRZMasson
