### ISSUE TITLE
Use version 0.69 on BabylonReactNativeSample

### ISSUE THREAD

**Issue by gomes042** [SergioRZMasson/BabylonReactNative-ReactNative0.65-Bugbash#8]

**Comment by gomes042** [comment]
Also needs changes on [CREATE.md](https://github.com/BabylonJS/BabylonReactNativeSample/blob/main/CREATE.md)

**Comment by SergioRZMasson** [comment]
@runtothedoor , I have an experimental implementation using 0.69 under the react-native-0-69 branch. If it is stable enough, we can update main with it at some point.

**Comment by MykhailoButkevych-MR** [comment]
@SergioRZMasson Can we update main to what is in `react-native-0-69` branch now?

**Comment by SergioRZMasson** [comment]
Hey @MykhailoButkevych-MR , we are currently investigating the following issue: https://github.com/BabylonJS/BabylonReactNative/issues/469 

and we are not sure it this is related to version 0.69 or not. I will wait we have a better understanding of this bug before updating main.

**Comment by nuzulasrar** [comment]
Is **Babylon.js** able to support lower than 0.69, such as 0.60 ?

**Comment by bghgary** [comment]
We are using 0.69 now.
